<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateApiClient>false</GenerateApiClient>
  </PropertyGroup>

  <Import Project="../Common.Projects.props" />
  <Import Project="../Packable.Projects.props" />

  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="14.6.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Trakx.Common.ApiClient" Version="2.0.0" />
    <PackageReference Include="Trakx.Common.Configuration" Version="2.0.0" />
  </ItemGroup>

  <Target Name="NSwag" BeforeTargets="Build" Condition="'$(GenerateApiClient)'=='True' ">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net100) run nswag.json /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>

</Project>

