get:
  security:
    - bearerAuth: []
  summary: Get configuration information.
  description: Retrieves general configuration information.
  operationId: getConfig
  tags:
    - Management
  responses:
    '200':
      description: Successfully retrieved configuration information.
      headers:
        X-Request-Id:
          $ref: "../../v0.1.0/headers/XRequestId.yml"
      content:
        application/json:
          schema:
            properties:
              data:
                $ref: "../../v0.1.0/schemas/Configuration.yml"
